FROM node:14

MAINTAINER datapunt@amsterdam.nl

EXPOSE 80

RUN apt-get update && apt-get install -y git nginx && rm -rf /var/lib/apt/lists/*

COPY package.json /app/

WORKDIR /app

ENV PATH=./node_modules/.bin/:~/node_modules/.bin/:$PATH
RUN git config --global url."https://".insteadOf git:// && \
    git config --global url."https://github.com/".insteadOf git@github.com: && \
    yarn install && \
    chmod -R u+x node_modules/.bin/

COPY src /app/src
COPY test.sh /app
